In [1]:
# Importation of libraries
import pandas as pd
import numpy as np

In [2]:
#loading of files and merging the both of them
df1 = pd.read_csv("QVI_purchase_behaviour.csv")
df2 = pd.read_excel("QVI_transaction_data.xlsx")
df1.head(5)
df2.head(5)

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

In [3]:
df1.head(5)

   LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0            1000   YOUNG SINGLES/COUPLES          Premium
1            1002   YOUNG SINGLES/COUPLES       Mainstream
2            1003          YOUNG FAMILIES           Budget
3            1004   OLDER SINGLES/COUPLES       Mainstream
4            1005  MIDAGE SINGLES/COUPLES       Mainstream

In [5]:
# I will merge on lylty_card_nbr since that is the column the two datasets have in common
df = pd.merge(df1,df2,on="LYLTY_CARD_NBR")
df.head(5)

,LYLTY_CARD_NBR,LIFESTAGE,PREMIUM_CUSTOMER,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,1000,YOUNG SINGLES/COUPLES,Premium,43390,1,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,1002,YOUNG SINGLES/COUPLES,Mainstream,43359,1,2,58,Red Rock Deli Chikn&Garlic Aioli 150g,1,2.7
2,1003,YOUNG FAMILIES,Budget,43531,1,3,52,Grain Waves Sour Cream&Chives 210G,1,3.6
3,1003,YOUNG FAMILIES,Budget,43532,1,4,106,Natural ChipCo Hony Soy Chckn175g,1,3.0
4,1004,OLDER SINGLES/COUPLES,Mainstream,43406,1,5,96,WW Original Stacked Chips 160g,1,1.9

In [6]:
# Exploratory function
def explore_data(df):
    print("Shape of dataset:",df.shape)
    print("\nColumns: \n", df.columns)
    print("\nData types:\n", df.dtypes)
    print("\nMissing values:\n", df.isnull().sum())
    print("\nSummary statistics:\n", df.describe())

In [7]:
explore_data(df)

Shape of dataset: (264836, 10)

Columns:
 Index(['LYLTY_CARD_NBR', 'LIFESTAGE', 'PREMIUM_CUSTOMER', 'DATE', 'STORE_NBR',
       'TXN_ID', 'PROD_NBR', 'PROD_NAME', 'PROD_QTY', 'TOT_SALES'],
      dtype='object')

Data types:
 LYLTY_CARD_NBR        int64
LIFESTAGE            object
PREMIUM_CUSTOMER     object
DATE                  int64
STORE_NBR             int64
TXN_ID                int64
PROD_NBR              int64
PROD_NAME            object
PROD_QTY              int64
TOT_SALES           float64
dtype: object

Missing values:
 LYLTY_CARD_NBR      0
LIFESTAGE           0
PREMIUM_CUSTOMER    0
DATE                0
STORE_NBR           0
TXN_ID              0
PROD_NBR            0
PROD_NAME           0
PROD_QTY            0
TOT_SALES           0
dtype: int64

Summary statistics:
        LYLTY_CARD_NBR           DATE     STORE_NBR        TXN_ID  \
count    2.648360e+05  264836.000000  264836.00000  2.648360e+05
mean     1.355495e+05   43464.036260     135.08011  1.351583e+05
std      8.057998e+04     105.389282      76.78418  7.813303e+04
min      1.000000e+03   43282.000000       1.00000  1.000000e+00
25%      7.002100e+04   43373.000000      70.00000  6.760150e+04
50%      1.303575e+05   43464.000000     130.00000  1.351375e+05
75%      2.030942e+05   43555.000000     203.00000  2.027012e+05
max      2.373711e+06   43646.000000     272.00000  2.415841e+06

            PROD_NBR       PROD_QTY      TOT_SALES
count  264836.000000  264836.000000  264836.000000
mean       56.583157       1.907309       7.304200
std        32.826638       0.643654       3.083226
min         1.000000       1.000000       1.500000
25%        28.000000       2.000000       5.400000
50%        56.000000       2.000000       7.400000
75%        85.000000       2.000000       9.200000
max       114.000000     200.000000     650.000000

 The columns of PROD_QTY and TOT_SALES show signs of outliers present, but with limited information it can be said that those might
 be bulk purchase so i want to check for a correlation between those that have max product qty and high total sales

In [8]:
df[df['PROD_QTY']==200]

,LYLTY_CARD_NBR,LIFESTAGE,PREMIUM_CUSTOMER,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
221625,226000,OLDER FAMILIES,Premium,43331,226,226201,4,Dorito Corn Chp Supreme 380g,200,650.0
221626,226000,OLDER FAMILIES,Premium,43605,226,226210,4,Dorito Corn Chp Supreme 380g,200,650.0

In [9]:
(df['PROD_QTY']==200).sum()

2

In [12]:
df['PROD_QTY'].value_counts()

PROD_QTY
2      236039
1       27518
5         450
3         430
4         397
200         2
Name: count, dtype: int64

- I now realize that it would have most likely been a bulk order from premium customer

In [15]:
# let us clean our data futher
def clean_data(df):
    # Drop duplicates
    df= df.drop_duplicates()
    # Handle missing values if any although our data has none
    df= df.fillna(method='ffill')
    return df

In [16]:
clean_data(df)

C:\Users\SEITUWA\AppData\Local\Temp\ipykernel_7548\1206826937.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df= df.fillna(method='ffill')

,LYLTY_CARD_NBR,LIFESTAGE,PREMIUM_CUSTOMER,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,1000,YOUNG SINGLES/COUPLES,Premium,43390,1,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,1002,YOUNG SINGLES/COUPLES,Mainstream,43359,1,2,58,Red Rock Deli Chikn&Garlic Aioli 150g,1,2.7
2,1003,YOUNG FAMILIES,Budget,43531,1,3,52,Grain Waves Sour Cream&Chives 210G,1,3.6
3,1003,YOUNG FAMILIES,Budget,43532,1,4,106,Natural ChipCo Hony Soy Chckn175g,1,3.0
4,1004,OLDER SINGLES/COUPLES,Mainstream,43406,1,5,96,WW Original Stacked Chips 160g,1,1.9
...,...,...,...,...,...,...,...,...,...,...
264831,2370701,YOUNG FAMILIES,Mainstream,43442,88,240378,24,Grain Waves Sweet Chilli 210g,2,7.2
264832,2370751,YOUNG FAMILIES,Premium,43374,88,240394,60,Kettle Tortilla ChpsFeta&Garlic 150g,2,9.2
264833,2370961,OLDER FAMILIES,Budget,43397,88,240480,70,Tyrrells Crisps Lightly Salted 165g,2,8.4
264834,2370961,OLDER FAMILIES,Budget,43400,88,240481,65,Old El Paso Salsa Dip Chnky Tom Ht300g,2,10.2
264835,2373711,YOUNG SINGLES/COUPLES,Mainstream,43448,88,241815,16,Smiths Crinkle Chips Salt & Vinegar 330g,2,11.4

In [21]:
df.groupby(['LYLTY_CARD_NBR','PREMIUM_CUSTOMER','LIFESTAGE','PROD_NAME', 'PROD_QTY'])['TOT_SALES'].sum().sort_values(ascending=False)

LYLTY_CARD_NBR  PREMIUM_CUSTOMER  LIFESTAGE               PROD_NAME                               PROD_QTY
226000          Premium           OLDER FAMILIES          Dorito Corn Chp     Supreme 380g        200         1300.0
7041            Budget            YOUNG SINGLES/COUPLES   Dorito Corn Chp     Supreme 380g        2             39.0
155224          Mainstream        YOUNG FAMILIES          Dorito Corn Chp     Supreme 380g        2             39.0
210110          Mainstream        YOUNG FAMILIES          Dorito Corn Chp     Supreme 380g        2             39.0
172167          Budget            YOUNG FAMILIES          Smiths Crnkle Chip  Orgnl Big Bag 380g  2             35.4
                                                                                                               ...
77066           Budget            YOUNG SINGLES/COUPLES   Woolworths Medium   Salsa 300g          1              1.5
53176           Budget            OLDER SINGLES/COUPLES   Woolworths Medium   Salsa 300g          1              1.5
256071          Mainstream        MIDAGE SINGLES/COUPLES  Woolworths Mild     Salsa 300g          1              1.5
233444          Premium           MIDAGE SINGLES/COUPLES  Woolworths Medium   Salsa 300g          1              1.5
73132           Mainstream        OLDER SINGLES/COUPLES   Woolworths Mild     Salsa 300g          1              1.5
Name: TOT_SALES, Length: 258954, dtype: float64

In [23]:
df['DATE'] = pd.to_datetime(df['DATE'], origin='1899-12-30', unit='D')
df

,LYLTY_CARD_NBR,LIFESTAGE,PREMIUM_CUSTOMER,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,1000,YOUNG SINGLES/COUPLES,Premium,2018-10-17,1,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,1002,YOUNG SINGLES/COUPLES,Mainstream,2018-09-16,1,2,58,Red Rock Deli Chikn&Garlic Aioli 150g,1,2.7
2,1003,YOUNG FAMILIES,Budget,2019-03-07,1,3,52,Grain Waves Sour Cream&Chives 210G,1,3.6
3,1003,YOUNG FAMILIES,Budget,2019-03-08,1,4,106,Natural ChipCo Hony Soy Chckn175g,1,3.0
4,1004,OLDER SINGLES/COUPLES,Mainstream,2018-11-02,1,5,96,WW Original Stacked Chips 160g,1,1.9
...,...,...,...,...,...,...,...,...,...,...
264831,2370701,YOUNG FAMILIES,Mainstream,2018-12-08,88,240378,24,Grain Waves Sweet Chilli 210g,2,7.2
264832,2370751,YOUNG FAMILIES,Premium,2018-10-01,88,240394,60,Kettle Tortilla ChpsFeta&Garlic 150g,2,9.2
264833,2370961,OLDER FAMILIES,Budget,2018-10-24,88,240480,70,Tyrrells Crisps Lightly Salted 165g,2,8.4
264834,2370961,OLDER FAMILIES,Budget,2018-10-27,88,240481,65,Old El Paso Salsa Dip Chnky Tom Ht300g,2,10.2
264835,2373711,YOUNG SINGLES/COUPLES,Mainstream,2018-12-14,88,241815,16,Smiths Crinkle Chips Salt & Vinegar 330g,2,11.4

In [24]:
df.to_csv("Quantum.csv", index=False)